### ISSUE TITLE
How to make cargo binaries runnable with lit?

### ISSUE THREAD

**Issue by sheredom** [dylanmckay/lit#3]
So I created this little test project to illustrate the problem I had https://github.com/sheredom/lit-test and https://travis-ci.org/sheredom/lit-test/builds/522554330.

As (I hope!) you can see - the travis job fails for linux & Mac but passes for Windows. It seems that your awesome lit crate on Windows can find executables built by cargo, but not for Mac/linux?

Thanks for any help! Love the lib :)

**Comment by dylanmckay** [comment]
> As (I hope!) you can see - the travis job fails for linux & Mac but passes for Windows. It seems that your awesome lit crate on Windows can find executables built by cargo, but not for Mac/linux?

Surprising, I've never used this crate on Windows before, only on Linux and Mac.

The code that does the executable lookup is located [here](https://github.com/dylanmckay/avr-compiler-integration-tests/blob/master/src/avr-lit/main.rs#L153). It isn't very smart, it just looks in the `$PATH` and nothing else.

I think that perhaps, on Travis CI Windows for some reason the artifact directory `target/debug/...` folder is somehow in the OS path variable.

As far as I can tell, no explicit logic exists that intentionally adds the `cargo` `target/` directory to the search path.

You have two ways of working around this: manually appending to `PATH` in your test harness before passing execution to `lit`, or modifying `lit` to support this behaviour (for which I would happily accept a patch!)

I hope that helps!

**Comment by sheredom** [comment]
Oh damn I forgot to say that it worked, and you could close this. Doh!
